### PR TITLE
multiple problems: Remove non-ASCII characters to fix #441

### LINKED ISSUE #441: Update or remove non-ASCII test cases.
In https://github.com/exercism/x-common/issues/428 the decision was made to remove test cases containing non-ASCII characers from exercises that are not explicitly about extended character set handling.

The following tests were identified as containing test cases that need to be fixed:

- [x] exercises/atbash-cipher/canonical-data.json
- [x] exercises/bob/canonical-data.json
- [x] exercises/forth/canonical-data.json
- [x] exercises/isogram/canonical-data.json
- [x] exercises/pangram/canonical-data.json
- [x] exercises/run-length-encoding/canonical-data.json
- [x] exercises/scrabble-score/canonical-data.json

Please check before removing a test that it is not **also testing another property of the solution**. If it is, please update the test to remove the non-ascii characters while maintaining the other intended purpose.

### PR DESCRIPTION
**Pull request by robkeim**
#441

### CODE REVIEW

**Comment by Insti** [comment]
I'm not sure putting changes to multiple problems in the same commit is a good idea.

Are you sure that these tests are not also testing another aspect of the solution?

**Comment by robkeim** [comment]
@Insti should I create three different PRs then?

I looked through the tests and given the titles they are explicitly testing non-ASCII functionality. I don't have any way of validating if the original intent of the test was to cover two different things though.

**Comment by Insti** [comment]
3 commits would be good.

It's good to ask yourself, "Might I need to revert part of this?".

**Comment by robkeim** [comment]
Ok sounds good @Insti

I've got a couple of follow-up questions:
- What is the best way to update this to 3 separate commits? Do I simply abandon this PR and start a new one, or is there some ninja git trick I'm missing?
- Don't we do a "squash and merge" when merging into master? In that case, the intermediate commits are going to be lost right?

**Comment by petertseng** [comment]
> What is the best way to update this to 3 separate commits?

The way I like to do this is `git reset origin/master`, then use `git add -p` to add each change separately, with `git commit` for each commit. You will need to `push --force` when done.

> Don't we do a "squash and merge" when merging into master?

I would recommend not doing so if there are separate commits that are meant to stay separate. Only squash and merge if there is one commit in the PR, or if the commits in the PR are meant to be squashed.

**Comment by robkeim** [comment]
Thanks @petertseng for the tip, although the forced push didn't go well so I had to delete the remote branch and start again :(

The new PR is #529

**Pull request closed without merging**
