### PR TITLE
Add descriptions to Roman numerals canonical data.

### PR DESCRIPTION
**Pull request by stevejb71**
Descriptions could be worked out programatically (or by a human), but:
1. this entails more work for an automated test generator, which is not needed elsewhere as most (if not all) other data files provide descriptions.
2. descriptions won't be consistent across streams

### CODE REVIEW

**Comment by Insti** [comment]
@stevejb71 thanks for your work on this, it's good for all test data files to have descriptions.

However, the descriptions need to be useful. As you've said yourself these descriptions could be derived from information already in the file, so they are not adding any value, and cross stream consistency of error messages is a very unimportant thing.

A description should explain what a test is testing and why this test is important.

Have a look at [bowling](https://github.com/exercism/x-common/blob/master/exercises/bowling/canonical-data.json)
```
{
      "description": "a spare in the last frame gets a one roll bonus that is counted once",
      "rolls": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 3, 7],
      "expected": 17
},
```
This is a test to catch a common implementation bug that would cause the bonus roll to be counted twice.

And note how that is different from:
```
      "description": "when rolling [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 3, 7] the game score is 17"
```

Roman numerals is a hard, because it's easy to fall into the trap you have and just make a simple in -> out mapping.

Think about why each number is being tested.
Why is 1 there?
Why is 7 NOT there?
Why is there no test for 10?

If you do this process fully you'll find test cases that are missing and test cases that are redundant, but at the end you'll have a set of tests with descriptions that do usefully and clearly describe the problem.

**Comment by stevejb71** [comment]
I'll take a look, it's a little hard to form good concise descriptions of these tests.

**Comment by ErikSchierboom** [comment]
@stevejb71 A little bump :) Are you still interested in working on this PR? 

Coming up with good descriptions can be hard, but I think it is possible here. There is a very nice post on the F# for fun and profit website on [implementing Roman Numerals in F#](https://fsharpforfunandprofit.com/posts/roman-numerals/). In that post, several requirements are listed:

- Five in a row of any digit is not allowed
- Some digits are allowed in runs of up to 4. They are I,X,C, and M. The others (V,L,D) can only appear singly.
- Some lower digits can come before a higher digit, but only if they appear singly. E.g. "IX" is ok but "IIIX" is not.
- But this is only for pairs of digits. Three ascending numbers in a row is invalid. E.g. "IX" is ok but "IXC" is not.
- A single digit with no runs is always allowed

Perhaps you can use those requirements as an inspiration for test descriptions (and test data)?

**Comment by stevejb71** [comment]
There look to be some good ideas in that article such should help me get started. 

May take a few weeks, I've got a holiday coming up shortly.

**Comment by ErikSchierboom** [comment]
@stevejb71 Good luck with it. And enjoy your holiday :)

**Comment by rbasso** [comment]
Hi,

We're mostly finishing #625, and `roman-numerals` is one of the remaining problem to adapt to the new JSON Schema. The major problem with it is the lack of descriptions, which are enforced now.

Could we merge this the way it is to allow compliance and later fix it as someone comes up with better descriptions?

**Comment by petertseng** [comment]
Erm well I can offer my descriptions that I tried to cook up for this special occasion just now, but it's a bit unfortunate because for example the description for the 93 test implies it is only testing 90, but it is testing 90 + 3.

```diff
commit e0d2ef21511f0ce1d4814b17a3cb644d2baba40e (HEAD -> roman-desc)
Author: Peter Tseng <pht24@cornell.edu>
Date:   Sat Mar 11 04:18:09 2017 -0800

    roman-numerals: descriptions?

diff --git a/exercises/roman-numerals/canonical-data.json b/exercises/roman-numerals/canonical-data.json
index 9c5ee70..d17d4eb 100644
--- a/exercises/roman-numerals/canonical-data.json
+++ b/exercises/roman-numerals/canonical-data.json
@@ -1,74 +1,92 @@
 {
    "cases": [
       {
+         "description": "1 is a single I",
          "number" : 1, 
          "expected": "I"
       },
       {
+         "description": "2 is two I's",
          "number" : 2, 
          "expected": "II"
       },
       {
+         "description": "3 is three I's",
          "number" : 3, 
          "expected": "III"
       },
       {
+         "description": "4, being 5 - 1, is IV",
          "number" : 4, 
          "expected": "IV"
       },
       {
+         "description": "5 is a single V",
          "number" : 5, 
          "expected": "V"
       },
       {
+         "description": "6, being 5 + 1, is VI",
          "number" : 6, 
          "expected": "VI"
       },
       {
+         "description": "9, being 10 - 1, is IX",
          "number" : 9, 
          "expected": "IX"
       },
       {
+         "description": "20 is two X's",
          "number" : 27, 
          "expected": "XXVII"
       },
       {
+         "description": "48 is not 50 - 2 but rather 40 + 8",
          "number" : 48, 
          "expected": "XLVIII"
       },
       {
+         "description": "50 is a single L",
          "number" : 59, 
          "expected": "LIX"
       },
       {
+         "description": "90, being 100 - 10, is XC",
          "number" : 93, 
          "expected": "XCIII"
       },
       {
+         "description": "100 is a single C",
          "number" : 141, 
          "expected": "CXLI"
       },
       {
+         "description": "60, being 50 + 10, is LX",
          "number" : 163, 
          "expected": "CLXIII"
       },
       {
+         "description": "400, being 500 - 100, is CD",
          "number" : 402, 
          "expected": "CDII"
       },
       {
+         "description": "500 is a single D",
          "number" : 575, 
          "expected": "DLXXV"
       },
       {
+         "description": "900, being 1000 - 100, is CM",
          "number" : 911, 
          "expected": "CMXI"
       },
       {
+         "description": "1000 is a single M",
          "number" : 1024, 
          "expected": "MXXIV"
       },
       {
+         "description": "3000 is three M's",
          "number" : 3000, 
          "expected": "MMM"
       }
```

**Comment by petertseng** [comment]
It's in a PR now so y'all can comment on it if y'all care.

**Pull request closed without merging**
