### PR TITLE
deprecated file added for Binary and related

### PR DESCRIPTION
**Pull request by kotp**
re: #279

### CODE REVIEW

**Comment by kotp** [comment]
Will need to mark a few boxes off [here](https://github.com/exercism/x-common/issues/279#issue-161866511)

**Comment by petertseng** [comment]
Just as it was [suggested of me](https://github.com/exercism/x-common/pull/532), now in turn I suggest of others:

Why don't we put in the .deprecated file a link to the issue https://github.com/exercism/x-common/issues/276 where the exercises were deprecated, and a suggestion to consider their replacement all-your-base instead

**Comment by ErikSchierboom** [comment]
LGTM!

**Comment by kotp** [comment]
Marking off the boxes mentioned...

**Pull request merged**
