### PR TITLE
Fixed README for palindrome-products #208

### PR DESCRIPTION
**Pull request by remcopeereboom**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Great work!

**Comment by kotp** [comment]
I restarted the build on this, after 3 hours of it apparently running.

**Comment by robkeim** [comment]
Nice work @remcopeereboom!

**Comment by remcopeereboom** [comment]
Does anyone have an idea why Travis isn't building? It says the master branch was building when I forked it and I can't see how the markdown file would break it.

**Comment by robkeim** [comment]
Looks like it's passed now!

**Pull request merged**
