### PR TITLE
Clarify handling scores greater than 255 in allergies.

### PR DESCRIPTION
**Pull request by jtigger**

### CODE REVIEW

**Comment by jtigger** [comment]
Addresses #224.

Expressed in solution-agnostic terms.

**Comment by IanWhitney** [comment]
Just to make sure I understand, this change would mean that a test of 257 would be allergic to all the items mentioned in the readme?

**Comment by NobbZ** [comment]
As I understand it the read me asks for a simple modulo equivalency.

Ian Whitney <notifications@github.com> schrieb am Sa., 1. Okt. 2016 14:56:

**Comment by Insti** [comment]
257 would mean allergic to eggs (1)

**Comment by jtigger** [comment]
The modification of the description plus the final test in suite implied by the `canonical-data.json` would mean that a score of 257 would mean some uncodified allergen (256) plus eggs(1), the former to be ignored/masked/modulo'ed.

**Comment by IanWhitney** [comment]
Ok. That's not how this change reads for me. 

> Note: a given score may include allergens not listed above (i.e. allergens that score 256, 512, 1024, etc.). Your program should ignore those components of the score

The "ignore those components" could be clearer. Maybe:

> Note: Allergens with higher scores (i.e., 256, 512, 1024) should be ignored. For example, a score of 257 would be allergic to just Eggs.

**Comment by jtigger** [comment]
Added example to the description.  Thanks, @IanWhitney.

**Comment by kytrinyx** [comment]
This looks good to me. Thanks for hashing out the details on this!

**Pull request merged**
