### PR TITLE
Added difference-of-squares.json test definition

### PR DESCRIPTION
**Pull request by mike-hewitson**
Some extra comments as this one brought in a few new challenges. Hope you like my approach.

### CODE REVIEW

**Comment by soniakeys** [comment]
It's workable, but I would prefer that test cases for different methods be grouped in separate json objects.  See for example clock.json and custom-set.json.  I do agree that the consistent difference checks don't need anything extra from the json.

**Comment by mikeyjcat** [comment]
@soniakeys Let me have a look at it and see how it would work out with the generator.

**Comment by kytrinyx** [comment]
@mikeyjcat the generators are written separately for each problem for exactly this reason.

**Comment by mikeyjcat** [comment]
@soniakeys Wouldn't this change the order of the tests for all languages? Currently the tests fir a specific number are grouped together (e.g. sum of squares, square of sums, difference, all together for 5). If we were to group together by function, then we'd intersperse them, which I think would affect the understandability of the test suite? What do you think?

**Comment by soniakeys** [comment]
Maybe just some languages, but I think I see your point.  A problem though is that in your PR here, the grouping by number is implicit, not structural.  This means test programs (or generators) must include some logic to see which fields are present or missing.  If objects have a more consistent structure, test programs and generators stay simpler.  So, for example, the three results could all be included in a single object, like

```
{
   "input": 5,
   "square-of-sums": 225,
   "sum-of-squares": 55,
   "difference": 170
}
```

Then each object could have the same structure.

**Comment by mikeyjcat** [comment]
@soniakeys I think your suggestion is great, and I like it. I'll rework the generator and see how it goes, and let you know.

**Comment by soniakeys** [comment]
@kytrinyx this grouping by number still leaves it easy for test program to order tests by method if they like.  They just run through the list of test cases multiple times, once for each method they are testing.

**Comment by kytrinyx** [comment]
@soniakeys Agreed, your suggestion is simpler.

**Comment by mikeyjcat** [comment]
Yep, I just need to work out how to do it elegantly. We've got the test names (n) , input data (1), and methods (n) (not sure what the language agnostic word is). The pattern we've been considering suggested by Sonia doesn't consider the test name, and I want to check the idea against the other test definitions to see if anything else emerges. This seems to be my experience for each one I've done so far:)

**Comment by kytrinyx** [comment]
That sounds like a plan. We don't need test names in Go, since we use table tests rather than individual tests. That said, a description for each test case can be useful in some situations, and in languages like Ruby where we have individual tests, the description can be used as the name.

I have to board my flight. I'll think about how to name the thing that becomes method/function.

**Comment by kytrinyx** [comment]
@mikeyjcat I never came up with any good word for method/function, but on reconsidering this discussion, I don' think it needs it. Also, I don't think that a test name is necessary. Each language can construct the name based on the test data however they like. It will depend on whether or not they put these in the same test or not.

**Comment by kytrinyx** [comment]
@mike-hewitson Would you mind taking a look at this to see if we can take it across the finish line?

**Comment by mike-hewitson** [comment]
Will do, apologies. I'll get it done this weekend.

**Comment by petertseng** [comment]
Oof, realized too late that we had two people do this: https://github.com/exercism/x-common/pull/146

**Comment by kytrinyx** [comment]
Aaah, in that case, apologies for the mixup! I'm going to go ahead and close this one. Thanks all!

**Pull request closed without merging**
