### PR TITLE
Add filecheck script to check for essential files

### LINKED ISSUE #457: Fail the travis build if an exercise is missing critical files
Everything on Exercism assumes that an exercise has at the very least a `description.md` file and a `metadata.yml` file.

If one of these files is missing in an exercise, then the build should break.

See discussion here for context: https://github.com/exercism/trackler/pull/6/commits/036a2a7f579aa29e4815cf32dd285105a810de0b#r90053608

### PR DESCRIPTION
**Pull request by tejasbubane**
Check for presence of `description.md` and `metadata.yml`.
Add this script to travis build.

Fixes #457

### CODE REVIEW

**Comment by Insti** [comment]
Me too :)

**Comment by tejasbubane** [comment]
Yikes! 🙈

**Comment by kytrinyx** [comment]
:heart: :heart: :heart: to both of you! Let me look at both of these—and if you have an opinion on which we should merge, please speak up.

**Comment by kytrinyx** [comment]
I like that this prints the error to STDERR.

I'm on the fence about the progress thing. I actually have a philosophical thingy around CLIs and output (which I don't adhere to strictly, but which I think about a lot). I wrote about it here: http://whipperstacker.com/2015/10/05/silence-noisy-output-from-command-line-tools-by-monitoring-progress-with-siginfo/

I think in the case of x-common and builds and things it makes sense to include it, because we're going to be running it in a context where we're impatient for it to complete.

OK, @tejasbubane @Insti -- what do you think? Should we merge one or the other or combine some aspects of both?

**Comment by tejasbubane** [comment]
I liked @Insti's usage of `require_file` function. Maybe combine some aspects of both? I think the progress bar would go well with CI. And we should add some success message as well.

**Comment by Insti** [comment]
Shall we merge mine? It currently mostly works, and then anyone can contribute further improvements. It's a shame we duplicated our efforts on this one.

**Comment by tejasbubane** [comment]
> It's a shame we duplicated our efforts on this one.

Yeah we should call dibs as soon as possible (note to self)

> Shall we merge mine? It currently mostly works, and then anyone can contribute further improvements

Sounds good 👍

**Comment by Insti** [comment]
I've added errors to STDOUT and a `--progress` command line option. #458

**Comment by Insti** [comment]
Closed in favor of: #458 which does essentially the same thing.

Thanks for your work on this @tejasbubane, its unfortunate we both worked on the same feature at the same time.

I hope I'm not out of line by merging that one and closing this, but It's been a month, and no-one else was stepping forward to make the decision. If it's wrong we can always revert and do it the other way.

**Comment by tejasbubane** [comment]
No worries @Insti 👍

**Pull request closed without merging**
