### PR TITLE
Gigasecond exact time off

### PR DESCRIPTION
**Pull request by masters3d**
Found error on Daylight Savings

### CODE REVIEW

**Comment by kytrinyx** [comment]
This is a good point, however not all locations observe daylight savings time.

**Comment by masters3d** [comment]
that is right. I think the swift api may have a bug on this.

**Comment by masters3d** [comment]
I was wrong about this and that is why I closed the pull request. See spread sheet. 
image

**Comment by kytrinyx** [comment]
Thanks for following up.

**Pull request closed without merging**
