### PR TITLE
phone-number: 2 more tests

### PR DESCRIPTION
**Pull request by rpottsoh**
Added two tests that are included in the csharp track.

### CODE REVIEW

**Comment by petertseng** [comment]
We argued against including these tests in #477:

> implementing getting `country-code` from number and `pretty-printing` the number. I feel these should not be part of the exercise.

> Pretty printing and extracting subparts of numbers: Yeah, doesn't seem that important to me, and the README doesn't mention it, so I would not add them to the JSON file

So, shall we reverse this decision?

If we do, we need to add it to the README as well.

Also, I would like for these tests not to get mixed in with the parsing tests, because then the only way to tell what function is under test is the description, which is too much work for automated test generators. We wouldn't want to make them build in natural language parsing to figure out what function to test based on the description. We would rather put them in a separate section. An example is https://github.com/exercism/x-common/blob/master/exercises/difference-of-squares/canonical-data.json, where there are separate section for `sum_of_squares` and `square_of_sum`.

I haven't changed my mind yet, so I still suggest not having these tests.

**Comment by rpottsoh** [comment]
I'm fine with whatever decision the group makes.  I was not aware of the previous discussion.

There were tests in the json that were not in csharp and vice versa.

If these two extra tests are nixed I can easily remove them from xpascal.

*csharp was the reference I used for xpascal.



Sent from my android device.

**Comment by Insti** [comment]
I vote for excluding anything other than validation from the test suite.

**Comment by Insti** [comment]
sorry, misclicked close

**Pull request closed without merging**
