### PR TITLE
diamond: add canonical data

### LINKED ISSUE #556: diamond: Implement canonical-data.json
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Diamond exercise can be found in the [./exercises/diamond/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/diamond for the up-to-date list of
language tracks that have an implementation of the Diamond exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/diamond

### PR DESCRIPTION
**Pull request by stkent**
Closes #556. See that issue for background information. Please contribute any new comments in this PR. Thanks!

I'm far from a property-based testing expert, so my explanation in the test data comment is likely clumsy. Please feel free to explain how to refine it!

I attempted to follow the proposed canonical data spec from https://github.com/exercism/x-common/pull/602. If you spot any deviations from the proposal, please let me know and I can correct them. cc @rbasso for his expertise and validation 😄

### CODE REVIEW

**Comment by stkent** [comment]
@rbasso thanks! 👍  @ spec!

**Comment by ErikSchierboom** [comment]
@stkent Do you want to modify the canonical-data of this PR (e.g. due to the discussion in #614), or shall we merge it?

**Comment by stkent** [comment]
@ErikSchierboom sorry, I don't quite follow; what was the modification you had in mind? Thanks!

**Comment by ErikSchierboom** [comment]
@stkent Oh sorry, I meant the bit about "print". There was some discussion if "print" was a good name, as it might imply that we were printing to the console instead of returning a string.

**Comment by stkent** [comment]
Ah, I'm with you now. Yes, let's change that - easy fix at this point. Incoming!

**Comment by stkent** [comment]
@ErikSchierboom I updated `print` to `rows`, but I'm open to other suggestions if that's not clear enough. (I'm thinking that with an updated description and the expected output as context, it should be ok?)

**Comment by ErikSchierboom** [comment]
@stkent I think `rows` is a good choice. :+1:

**Pull request merged**
