### PR TITLE
run-length-encoding: Add whitespace tests

### PR DESCRIPTION
**Pull request by DesHorsley**
Adds tests to check encoding and decoding of whitespace characters leaves the characters unchanged as per the description.md instructions.

### CODE REVIEW

**Comment by behrtam** [comment]
Just discovered #537 which changed the way white space is handled.

So we really want to change all the implementations in the tracks as for example python treats white spaces like other chars, so the result would look like this `encode("  hsqq qww  ") == '2 hs2q q2w2 '`.

**Comment by DesHorsley** [comment]
I agree that there is no reason to ignore it, other than my understanding of the description of the exersize, stating the whitespace should pass through unchanged. Perhaps the description should be amended to make it clear that white space should be treated as any other character?

**Comment by DesHorsley** [comment]
@behrtam how would you like me to proceed? I'm happy to contribute where I can. 

Is it just a case of updating the exercise description to remove the ambiguity and state whitespace is treated like the other characters?

**Comment by DesHorsley** [comment]
Closed as per #613

**Pull request closed without merging**
