### PR TITLE
Add Extensions to RobotName

### PR DESCRIPTION
**Pull request by masters3d**
https://github.com/exercism/x-common/issues/731

### CODE REVIEW

**Comment by masters3d** [comment]
What do u think?

**Comment by Insti** [comment]
The unique robot name part was what made this problem interesting.
I would prefer it remained as a main part of the exercise.

**Comment by masters3d** [comment]
Define unique? Have you gotten a chance to read the linked issue?

**Comment by Insti** [comment]
> Define unique?

From the description:

> Your solution should not allow the use of the same name twice 

I have read the linked issue, do you need me to post my objection there as well?

**Comment by masters3d** [comment]
That part it still part of the description.  I am afraid that most of the tracks have chosen only to test about 10k permutations which is different that's the 600k permutations needed for a truly unique test.

**Comment by Insti** [comment]
> most of the tracks have chosen only to test about 10k permutations which is different that's the 600k permutations needed for a truly unique test.

That's a deficiency of the tracks rather than an issue with the problem.
I believe the problem is good and it is the tests that need updating.

**Comment by masters3d** [comment]
Not when that kind of test was specified like this 

"In some exercism language tracks there are tests to ensure that the same name is never used twice."

That makes it sound optional. That is not the core concept of the exercise from the description.

**Pull request closed without merging**
