### PR TITLE
grep: Make exercise schema-compliant

### PR DESCRIPTION
**Pull request by rbasso**
This exercise has 3 text files encoded in the `canonical-data.json`, which is incompatible with the new JSON schema.

We are discussing in #699 what is the best way to deal with sharing test data among test cases, and it seems there isn't much support for adding this feature to the schema.

Anyway, that discussion doesn't need to suspend the migration of the current test data.

I proposed here to simply move the encoded files to the comments and proceed with the migration.

Related to #625.

### CODE REVIEW

**Comment by rbasso** [comment]
This exercise has 3 text files encoded in the `canonical-data.json`, which is incompatible with the new JSON schema.

We are discussing in #699 what is the best way to deal with sharing test data among test cases, and it seems there isn't much support for adding this feature to the schema.

Anyway, that discussion doesn't need to suspend the migration of the current test data.

I proposed here simply moving the encoded files to the comments and proceed with the migration.

Related to #625.

**Comment by rbasso** [comment]
Updated to fix some minor formatting issues.

**Comment by rbasso** [comment]
> I wonder if any language track will complain that it's too hard to extract the files from the comments (find lines surrounded by |, strip trailing newlines), but someone comes and argues for it I can't really argue on their behalf.

I was not even considering the possibility of algorithmically extracting the lyrics from the comments, @petertseng. 😄 

I think this PR is just an immediate solution for preserving the lyrics and allow compliance. I would really like to see a rewriting of this exercise allowing more automatic test generation, but waiting for it would postpone #625, and I think that it would be good no have #658 merged soon to enforce compliance in Travis-CI.

**Comment by petertseng** [comment]
Found out I missed a word:

> but someone comes and argues

but **until** someone comes and argues

**Pull request merged**
