### PR TITLE
Add sum-of-multiples.json

### PR DESCRIPTION
**Pull request by petertseng**
This is a synthesis of the existing tests in current tracks.

A short attempt to discern the history of the various tests:

Almost all tracks have the [3, 5] cases in common, as well as the
[7, 13, 17] and [43, 47] case. Indeed, these cases were present since
the first known sighting of sum-of-multiples at
https://github.com/exercism/exercism.io/commit/607be68494d30487c001303b6dc56c2b7b975409.

The [3, 5] to 100 case was added after discussion in
https://github.com/exercism/todo/issues/20 and
https://github.com/exercism/exercism.io/issues/2486. Most tracks had
adopted them at the time of this PR.

The [4, 6] and [5, 6, 8] cases arose from discussion in
https://github.com/exercism/exercism.io/issues/2341 - some tracks, but
not all, had adopted these tests at the time of this PR.

The [5, 25] case was a Haskell-specific case added in
https://github.com/exercism/xhaskell/pull/50.

The [] and [1] cases were Go-specific cases that have been present ever
since the exercise was added to the Go track in
https://github.com/exercism/xgo/pull/53.

Cases found in various tracks that were not included:

The [1] case of Go was originally a [1, 1] case but this is a conscious
decision not to test duplicate factors.

There were [0] and [0, 1] cases added to the Python track in
https://github.com/exercism/xpython/pull/149 but this is a conscious
decision not to test 0 as a factor.

This is the second subtask of #198.

Closes https://github.com/exercism/todo/issues/154

### CODE REVIEW

**Comment by petertseng** [comment]
Discussion is welcomed on whether to include tests for:

* Having duplicates in the list of factors
* Having 0 in the list of factors

**Comment by petertseng** [comment]
Verified no mistakes in this file:

```ruby
require 'json'

cases = JSON.parse(IO.read('sum-of-multiples.json'))

cases['cases'].each { |c|
  expected = c['expected']
  factors = c['factors']
  limit = c['limit']
  observed = (1...limit).select { |n|
    factors.any? { |f| n % f == 0 }
  }.reduce(0, :+)

  raise "Nope on #{c}, got #{expected}" if observed != expected
}

puts 'pass'
```

**Comment by kytrinyx** [comment]
I think that it's the right move to not test duplicate factors. Also, 0 is a really weird case, with the identify for multiplication being 1 and I'd rather not complicate this exercise with it.

I think that this PR is good as is, and would love a second (and third) opinion.

**Comment by petertseng** [comment]
Thanks for review. Just FYI I'm changing the commit message (the json file contents haven't changed) so as to reference https://github.com/exercism/todo/issues/20, as I missed it in my history exploration

**Comment by kytrinyx** [comment]
Excellent! Let me know if you run into any weirdness with blazon.

**Pull request merged**
