### PR TITLE
sublist: Make exercise schema-compliant

### PR DESCRIPTION
**Pull request by rbasso**
Related to #625.

### CODE REVIEW

**Comment by petertseng** [comment]
Surprise!

expectation -> expected please.

The only file to do that.

**Comment by petertseng** [comment]
Well, okay, I guess `expected` isn't **required** for compliance... but it would probably be better to use that, yes?

**Comment by rbasso** [comment]
I'm considering changing to `expectation` and also change the other two keys to camelCase, to conform with the Google JSON Style. What do you think about it?

**Comment by petertseng** [comment]
> I'm considering changing to expectation

Good!

> and also change the other two keys to camelCase

Seems good too! You also did it in rotational-cipher so why not here too!

**Comment by rbasso** [comment]
Updated!

**Comment by rbasso** [comment]
DONT MERGE YET

**Comment by rbasso** [comment]
The last commit (the only one hard to review) should be just formatting.

**Comment by petertseng** [comment]
I review commits that claim to be formatting-only with `git log -p -w`

Plus a small script to fetch arbitrary PRs:

```sh
#!/bin/sh

# remote of current branch is...
remotebranch=$(git rev-parse --abbrev-ref --symbolic-full-name @{u})
remote=$(echo "$remotebranch" | cut -d/ -f1)
echo "remote: $remote"

if [ $# -lt 2 ]; then
  echo "usage: $0 PR localbranch"
  exit 1
fi

git fetch $remote refs/pull/$1/head:$2
```

`git pr 705 sublist`

**Comment by rbasso** [comment]
Thanks! I'll try that later.

**Pull request merged**
