### PR TITLE
DO NOT MERGE: invalid json

### PR DESCRIPTION
**Pull request by petertseng**

### CODE REVIEW

**Comment by petertseng** [comment]
Thanks, that will be all for today.

**Comment by petertseng** [comment]
Wait hold on Travis needs to take it first

**Comment by petertseng** [comment]
ok

**Comment by petertseng** [comment]
https://travis-ci.org/exercism/x-common/builds/149102499

**Comment by petertseng** [comment]
Just going to make sure about Travis

**Comment by petertseng** [comment]
https://travis-ci.org/exercism/x-common/builds/158904921 is what I wanted to see.

**Comment by kytrinyx** [comment]
Good call, thank you!

**Pull request closed without merging**
