### PR TITLE
Remove Ruby code examples from simple-cipher README.

### PR DESCRIPTION
**Pull request by allyjweir**
Change made to make the examples language agnostic. I replaced the
code with written examples in the two cases where it made sense
and removed the final example as translating it didn't translate
well to plain English

### CODE REVIEW

**Comment by allyjweir** [comment]
Created in reference to issue #333

**Comment by allyjweir** [comment]
Created in reference to issue #312

**Comment by Insti** [comment]
Looks good :+1: 
I agree with removing the last example.

**Comment by kytrinyx** [comment]
Thank you!

**Pull request merged**
