### PR TITLE
robot name update

### PR DESCRIPTION
**Pull request by masters3d**
https://github.com/exercism/xecmascript/issues/263

### CODE REVIEW

**Comment by masters3d** [comment]
As a hint on how that can be accomplished? 
I'd rather remove even mentioning the last paragraph but since it is included some tracks have implemented but give no indication on how they are accomplishing it.

**Comment by ErikSchierboom** [comment]
@masters3d Ah, now I see what you are getting at. Although I wouldn't want to add this to the general README, you can have the CLI append text to the README for a specific exercise on a specific language track. This is precisely what you want, as you want to give your users a hint on how to solve this exercise.

To have the CLI append this extra information, just put a `HINTS.md` file in the exercise's directory. As an example, the C# track's `accumulate` exercise has a [HINTS.md](https://github.com/exercism/xcsharp/blob/master/exercises/accumulate/HINTS.md) file. The contents of this file will be append to the README when a user fetches the accumulate exercise in the C# track. 

I think adding a HINTS.md file to your track's version of the `robot-name` exercise is the better option than adding it to the shared x-common version.

**Comment by masters3d** [comment]
Thank you!

**Comment by ErikSchierboom** [comment]
You're welcome!

**Pull request closed without merging**
