### PR TITLE
sublist: Add digits edge case test

### PR DESCRIPTION
**Pull request by behrtam**
see #432

### CODE REVIEW

**Comment by Insti** [comment]
It can be good to copy/paste an issue description into the first post of a Pull request rather than just referencing it so reviewers can get an idea of what the issue being resolved is without having to look through external threads.

**Comment by petertseng** [comment]
More importantly, it would be good if that could be summarised in the commit message so that if I lack internet access and have the repo checked out but no access to Github, I can still understand why this test was aadded.

**Comment by kytrinyx** [comment]
@behrtam Would you mind amending the commit as @petertseng describes?

**Comment by tejasbubane** [comment]
@behrtam Can you update the commit message so we can get it merged in? Also while you are at it, please add `Fixes #issue-number` so that the issue is closed automatically once this PR is merged: https://help.github.com/articles/closing-issues-via-commit-messages/ and we don't need to remember to close it.

**Comment by behrtam** [comment]
I added the `Fixes #issue-number` reference to the commit message. Didn't know about that handy trick.
I won't duplicate the issue in the commit message. That doesn't feel right. If the issue would be a longer discussion and maybe even have references it self or images or something, where do we stop? ... copy/paste just to save one click?

**Comment by tejasbubane** [comment]
> I won't duplicate the issue in the commit message. That doesn't feel right. If the issue would be a longer discussion and maybe even have references it self or images or something, where do we stop? ... copy/paste just to save one click?

I agree with @Insti and @petertseng that a commit should have some context as to why this change was made. Refer: https://www.kernel.org/pub/software/scm/git/docs/git-commit.html#_discussion 
The commit message should be short (which is what you already have) and then there should be **description** which explains the commit. 
For more tips and details for writing good commit messages see this: http://chris.beams.io/posts/git-commit/

**Comment by Insti** [comment]
@behrtam it's good to be able to know what a commit is about by simply looking through the git logs on your local machine rather than requiring internet access and GitHub to be available.

**Comment by petertseng** [comment]
Seems like we have agreement. Thanks to all involved!

**Pull request merged**
