### PR TITLE
Documentaton: Improve the Porting to another exercises documentation

### PR DESCRIPTION
**Pull request by GustavoCaso**
exercism/todo#182

### CODE REVIEW

**Comment by kytrinyx** [comment]
@GustavoCaso Thanks! Would you mind rebasing this against the upstream master and pinging me with an `@`-mention when you've done so?

**Comment by GustavoCaso** [comment]
@kytrinyx I have no idea what just happens here ?? 😵

**Comment by Insti** [comment]
@GustavoCaso 

1) Do a `git rebase -i master`
There will be a big list of patches.
2) leave the first one as 'pick' then set all the rest to 'squash' 
3) Then go through the resulting combined message and keep just the bits that you changed.
4) Do a `git push --force` to re-write your branch.

**Comment by kytrinyx** [comment]
I think you would need to fetch the upstream first:

```
git fetch upstream master
git rebase -i upstream/master
```

**Comment by GustavoCaso** [comment]
@kytrinyx @Insti  I fixed the mess, thanks for the tips

**Comment by Cohen-Carlisle** [comment]
I'm going to bring this in as is. Thanks, @GustavoCaso! (fixes #182)

**Pull request merged**
