### PR TITLE
Reorganize the x-common files

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR reorganizes the X-common files as discussed in #269.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
For fun, this is the F# script I used to generate the new structure from the existing one:

```fsharp
open System
open System.IO

let rootDir = @"D:\programmeren\_persoonlijk\x-common"

let (</>) dir file = Path.Combine [| dir; file |]

let createDirectoryIfNotExists directory =
    if not <| Directory.Exists directory then
        Directory.CreateDirectory directory |> ignore

let copyFile source target = 
    if File.Exists source then
        File.Copy(source, target)

let createDirectory sourceMetadataFile =     
    let slug = Path.GetFileNameWithoutExtension sourceMetadataFile
    let sourceDataFile = rootDir </> (sprintf "%s.json" slug)
    let sourceDescriptionFile = rootDir </> (sprintf "%s.md" slug)
    let targetDirectory = rootDir </> "exercises" </> slug
    
    let targetMetadataFile = targetDirectory </> "metadata.yml"
    let targetDataFile = targetDirectory </> "data.json"
    let targetDescriptionFile = targetDirectory </> "description.md"
    
    createDirectoryIfNotExists targetDirectory

    copyFile sourceMetadataFile targetMetadataFile
    copyFile sourceDataFile targetDataFile
    copyFile sourceDescriptionFile targetDescriptionFile

let files = 
    Directory.EnumerateFiles(rootDir, "*.yml") 
    |> Seq.filter (fun x -> not <| x.EndsWith ".travis.yml")
    |> Seq.iter createDirectory
```

**Comment by Insti** [comment]
:+1: for script.

Should this PR move the existing files rather than adding new copies?
(and attempt to maintain the git history.)

**Comment by Insti** [comment]
I'd also like to see the individual filenames retain their slug prefix.

`exercises/accumulate/accumulate_data.json` rather than `exercises/accumulate/data.json`

This way, if you copy a file elsewhere to work on it you still have some idea what the data is and we don't end up with 100's of files called `data.json` that are required to be in the right place to know what they contain.

**Comment by ErikSchierboom** [comment]
I'm fairly certain the existing files should not be moved, as otherwise things will break.

As for renaming the files, that seems very redundant to me. If you want to work on the files, you will probably clone the whole repository and then the directory name already tells you the context. But maybe other people disagree?

**Comment by Insti** [comment]
[kytrinyx wrote:](https://github.com/exercism/x-common/issues/269#issuecomment-226472430)
> We can do this without breaking anything by making the API handle both cases, deploying that, and then moving all of the problems at once.

This PR would be the 'moving all the problems at once' step.
It's useful if this PR exists first, so that those testing the required api changes can use the branch to test against.

**Comment by Insti** [comment]
> As for renaming the files, that seems very redundant to me

I agree it is redundant, but what value does the filename `data` add?

**Comment by ErikSchierboom** [comment]
Not much, I agree. Perhaps it should be named `test-data.json`?

**Comment by kytrinyx** [comment]
> Not much, I agree. Perhaps it should be named test-data.json?

Yeah, that's better. Or `canonical-data.json`.

**Comment by ErikSchierboom** [comment]
I'll rename the files to `canonical-data.json`.

**Comment by ErikSchierboom** [comment]
@kytrinyx The test data JSON files have been renamed to `canonical-data.json`.

**Comment by kytrinyx** [comment]
Would you take a look at the CONTRIBUTING.md file and see if any references there need to be updated?

**Comment by ErikSchierboom** [comment]
I've started updating the `CONTRIBUTING.md` file. Would you mind taking a peek?

**Comment by kytrinyx** [comment]
The CONTRIBUTING.md updates look good to me.

**Comment by ErikSchierboom** [comment]
Is this something we want to merge, or should it be kept unmerged for a while?

**Comment by Insti** [comment]
Please keep unmerged.

The x-api changes are not complete.
+ This PR duplicates the exercise metadata files and obfuscates file histories.

**Comment by kytrinyx** [comment]
I think the TODO list is something like this:

- [ ] update this PR so that it moves files rather than copying them
- [ ] finalize and merge the x-api changes, deploy
- [ ] merge this PR, deploy
- [ ] update x-api to remove the logic that handles the deprecated file locations, deploy whenever

**Comment by ErikSchierboom** [comment]
@kytrinyx I've updated the PR to move the files instead of copying them.

**Comment by kytrinyx** [comment]
@ErikSchierboom The API change has been merged and is deploying. Would you mind rebasing this onto master to make sure we have all the latest changes and newest files?

**Comment by ErikSchierboom** [comment]
@kytrinx I've rebased this PR onto the latest master and also ran my script again to pickup the latest changes. I'll be away for a couple of days after today by the way, so I hopefully this is enough.

**Comment by Insti** [comment]
It's still showing +10k lines. I would expect a move to be almost zero if the + and - balance out from a move.

**Comment by ErikSchierboom** [comment]
I think it's because I forgot to remove the old files. I'll try to fix it tonight

**Comment by ErikSchierboom** [comment]
@Insti I've updated the PR. This time, I think everything is okay. cc @kytrinyx

**Comment by rbasso** [comment]
Great!
Any idea why `word-count.json` is the only file that seems to be copied instead of moved in *Files changed*?

**Comment by petertseng** [comment]
My blind guess (without verification of whether the guess is correct)

\r\n vs \n ?

**Comment by ErikSchierboom** [comment]
That would be my guess too

**Comment by ErikSchierboom** [comment]
@rbasso @petertseng It was indeed due to line-ending issues. I've fixed it and updated the PR>

**Comment by kytrinyx** [comment]
:tada: :tada: :tada:

**Comment by Insti** [comment]
Looks great, thanks @ErikSchierboom ! :heart:

**Comment by ErikSchierboom** [comment]
🎉

**Pull request merged**
