### PR TITLE
difference-of-squares: make short blurb consistent with full description

### PR DESCRIPTION
**Pull request by stkent**

### CODE REVIEW

**Comment by petertseng** [comment]
Er? I thought you did the reverse at #546. Did the long description change back again?

**Comment by petertseng** [comment]
Oh, no, you did the same in #546. Did someone change it back, then?

**Comment by petertseng** [comment]
Oh, I get it. #546 didn't target master. OK then.

**Comment by petertseng** [comment]
#546 is currently the only PR in the history of this entire repo that did not target master:

https://github.com/exercism/x-common/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20-base%3Amaster

**Comment by petertseng** [comment]
In that case, since this is the first time this commit will appear on master, I recommend the same commit message from #546 be reused. The fact that it is present in #546 will not be visible from someone who just clones the repo and uses `git log` without looking at github, so it is useful to have it.

**Comment by stkent** [comment]
@petertseng yeah, not sure what I was doing with that original branch! 😖  Updated the commit description to match the original!

**Comment by ErikSchierboom** [comment]
Thanks again @stkent!

**Pull request merged**
