### PR TITLE
bracket-push: add a test case

### PR DESCRIPTION
**Pull request by lex57ukr**
This helps cover broken stack-based implementations

### CODE REVIEW

**Comment by petertseng** [comment]
Thanks, test seems good

can we have bracket-push in the commit message as https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#pull-request-guidelines requests?

can we have version 1.1.0 since it falls under https://github.com/exercism/x-common/blob/master/README.md#minor-version-changes

**Comment by behrtam** [comment]
can we have imperative mood in the commit message: https://chris.beams.io/posts/git-commit/#imperative

**Comment by lex57ukr** [comment]
Will do

**Comment by lex57ukr** [comment]
All done. Thanks for your feedback!

**Comment by petertseng** [comment]
Musing to myself - we might consider whether some of the later cases in this file are made unnecessary by this case. I don't know what kinds of incorrect implementations people might come up with though.

**Pull request merged**
