### PR TITLE
perfect-numbers: description clarification

### PR DESCRIPTION
**Pull request by rootulp**
- add links to aliquot sum and Nicomachus
- provide examples of perfect, abundant, and deficient numbers
- provide instruction statement at bottom
- references #447

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
It's a great addition, although I think it would be slightly better if the added aliquot sum explanation was moved to just after "based on their aliquot sum.", which is just before their examples. That makes more sense to me.

**Comment by rootulp** [comment]
@ErikSchierboom great feedback! I reordered the text following your suggestion.

**Comment by ErikSchierboom** [comment]
@rootulp That's quick! LGTM!

**Comment by ErikSchierboom** [comment]
Merged. Thanks @rootulp! 🎉

**Pull request merged**
