### PR TITLE
Update pangram.json

### PR DESCRIPTION
**Pull request by istepura**
Based on https://github.com/exercism/xfsharp/pull/195. Test for edge case when panagram is not in target alphabet

### CODE REVIEW

**Comment by kytrinyx** [comment]
@petertseng @IanWhitney @ErikSchierboom you are the most likely to have opinions about this, I think.

**Comment by petertseng** [comment]
I feel more strongly about "the commits should be squashed before merge" than whether the test should be added.

But I would support the test to be added, since it looks to be the same as that added in https://github.com/exercism/xfsharp/pull/195/files and the reasoning for it seems sound. I assume there are solutions that pass "7h3 qu1ck brown fox jumps ov3r 7h3 lazy dog" but fail the new test? (Possibly because they remove numbers?)

**Comment by ErikSchierboom** [comment]
@petertseng Did you know that you can now squash the commits in the PR from within the GitHub interface? See [this article](https://help.github.com/articles/about-pull-request-merge-squashing/).

**Comment by tejasbubane** [comment]
Should we create issues in all language repos using `blazon`?

**Comment by Insti** [comment]
@tejasbubane that seems excessive for a minor test case addition.

**Comment by tejasbubane** [comment]
@Insti Agreed. 👍  This is an edge case anyways.

**Pull request merged**
