### PR TITLE
forth: Make exercise schema-compliant

### PR DESCRIPTION
**Pull request by rbasso**
Related to #625.

### CODE REVIEW

**Comment by petertseng** [comment]
>  I do question the `property`

I think there only needs to be a single value for it, `"evaluate"`

**Comment by rbasso** [comment]
You are completely right, @petertseng! Thanks for catching that! 👍

**Comment by rbasso** [comment]
You are completely right, @petertseng! Thanks for catching that! 👍 

Any recommendation for the property name? `run`? `forth`?

**Comment by petertseng** [comment]
My initial thought was `evaluate`, but your suggestions of `run` or `forth` seem reasonable as well. Since all seem reasonable, I suppose we can just pick one, since there will only be one for the exercise (unless we make changes! in which case we can rediscuss then)

**Comment by rbasso** [comment]
Rewritten with `evaluate`, @petertseng!

**Pull request merged**
