### PR TITLE
minesweeper: Add JSON test data

### PR DESCRIPTION
**Pull request by petertseng**
Implementing tracks:

* https://github.com/exercism/xelixir/blob/master/exercises/minesweeper/minesweeper_test.exs
* https://github.com/exercism/xfsharp/blob/master/exercises/minesweeper/MinesweeperTest.fs
* https://github.com/exercism/xgo/blob/master/exercises/minesweeper/minesweeper_test.go
* https://github.com/exercism/xhaskell/blob/master/exercises/minesweeper/test/Tests.hs
* https://github.com/exercism/xlua/blob/master/exercises/minesweeper/minesweeper_spec.lua
* https://github.com/exercism/xocaml/blob/master/exercises/minesweeper/test.ml
* https://github.com/exercism/xphp/blob/master/exercises/minesweeper/minesweeper_test.php
* https://github.com/exercism/xperl5/blob/master/minesweeper/minesweeper.t
* https://github.com/exercism/xpython/blob/master/exercises/minesweeper/minesweeper_test.py
* https://github.com/exercism/xruby/blob/master/exercises/minesweeper/minesweeper_test.rb
* https://github.com/exercism/xrust/blob/master/exercises/minesweeper/tests/minesweeper.rs
* https://github.com/exercism/xscala/blob/master/exercises/minesweeper/src/test/scala/MinesweeperTest.scala
* https://github.com/exercism/xswift/blob/master/exercises/minesweeper/MinesweeperTest.swift

The majority of tracks had a standard set of tests:
* zero size board
* empty board
* board full of mines
* eight mines, one space at the center
* horizontal line
* vertical line
* cross

Tracks that had these tests and no other:
* Elixir
* F#
* Haskell
* OCaml
* Scala

Tracks that checked for borders and invalid characters:
* Go
* Lua
* Perl
* PHP
* Python
* Ruby
* Swift

I decided not to test for borders nor invalid characters as they are not
in the README and they increase the scope of the exercise.

There were also various others:

* Large 6x6 board with 8 mines: Added.
* Large 5x5 board with 7 mines: Not added, didn't seem to provide extra
  value.
* One mine surrounded by spaces (Lua): Added.
* 1x1 board with one mine: Not added, seems same as 3x3 full of mines.
* 2x2 board full of mines: Not added, seems same as 3x3 full of mines.
* 5x5 board with two mines: Not added, didn't seem to provide extra
  value.
* 1x5, 5x1 board with mines on edges (Rust): Added, but combined.

Closes https://github.com/exercism/todo/issues/113

### CODE REVIEW

**Comment by petertseng** [comment]
Probably the most interesting decision we will make is: Should we check for borders and invalid characters? Take a look at any of the tracks listed if you want to know what the tests look like. Note that this is actually a majority of implementing tracks (7/13)!

I said no because I felt they increased the scope too much.

Then again, the README shows a board with a border, so if we don't want to test the border, maybe we should remove it. But maybe the border's just there so that the board stands out among the rest of the README...

**Comment by rbasso** [comment]
Good choices. Seems great! :+1:

**Comment by ErikSchierboom** [comment]
I agree with not testing for invalid characters or borders. This looks great!

**Comment by petertseng** [comment]
Surprisingly less controversial than I had thought it would be! I'll wait until Friday though.

**Comment by IanWhitney** [comment]
I'm on board. 👍

**Comment by kytrinyx** [comment]
I'm on board as well. 👍

**Pull request merged**
