### PR TITLE
Updated bracket-push tests

### PR DESCRIPTION
**Pull request by ebiven**
Tests for a class of problems where an unopened bracket is closed for
solutions which only track opened brackets.

### CODE REVIEW

**Comment by Insti** [comment]
Looks good to me.

**Comment by petertseng** [comment]
I was trying to figure out what kind of solution this rejects that aren't already covered by case `"}{"`, but I guess it's that `"}{"` is paired but in the wrong order, while the new case has a bracket that isn't paired at all? Do I have the idea right?

**Comment by ebiven** [comment]
Correct. This as a closing bracket that was never opened, but is otherwise valid. It identifies solutions like this that forget the third check.

* If opening bracket, push onto queue
* If closing bracket and matches last item added to queue, remove last item from queue
* If closing bracket and doesn't match last item in queue then unbalanced. <- This step
* Queue length should now equal 0.

**Comment by petertseng** [comment]
OK, and the idea is that `"}{"` does not identify those solutions since `"}{"` also has the trait that there is an unclosed open.

So the test cases were missing a test with only unopened closes, and this is one. OK, 👍  then.

**Pull request merged**
