### PR TITLE
Added a section on rebasing

### PR DESCRIPTION
**Pull request by heatherlim**
This is my first try at explaining rebasing.

### CODE REVIEW

**Comment by kytrinyx** [comment]
This is a good addition. Should we open by saying something like "You'll often be asked to rebase your branch before we merge a pull request." so that people have an idea why we're explaining this?

**Comment by heatherlim** [comment]
Yes, that sounds good.

**Comment by kytrinyx** [comment]
This looks great, would you mind squashing the commits, please?

**Comment by heatherlim** [comment]
Thanks, it's my first time at contributing to something.

**Comment by kytrinyx** [comment]
Thank you so much! (and congrats on your first open source commit :tada:)

**Pull request merged**
