### PR TITLE
difference-of-squares: add tests for boundary cases

### PR DESCRIPTION
**Pull request by weibeld**
See #789.

Zero is by some definitions regarded as a natural number, so an implementation should be able to handle this case, as well as the edge case of 1.

Summary of changes:

- Add tests for edge cases 0 and 1
- Remove test for input 10 (there are tests for 5 and 100 and if the implementation works for these numbers, it most likely also works for 10)
- Bump version number of the test suite to 1.1.0

I think the [description](https://github.com/exercism/x-common/blob/master/exercises/difference-of-squares/description.md) is ok, no need to include 0 there as it has anyway no influence on the result.

### CODE REVIEW

**Comment by Insti** [comment]
Great PR description 👍 :heart:

**Comment by Insti** [comment]
Is the ordering of these tests optimal?
Numeric order is tempting, but my preference would be for ease-of-implementation with the standard cases first followed by the edge cases.

**Comment by Insti** [comment]
Zero is not specified as one of the natural numbers, so I am not sure this is an appropriate test case in the canonical data.

**Comment by stkent** [comment]
+1 I would consider the 1-cases as the boundaries here, and remove the tests for 0, given the problem description.

**Comment by weibeld** [comment]
@Insti @stkent 

- Yes, the edge cases should come after the standard cases. I had the same thought too.
- I agree that it's probably better to take 1 as the edge case and drop 0. It would be more consistent with the problem description which requires a result only for numbers >= 1. (And actually, most solution that I just checked would already handle 0 correctly.)

I'm going to commit these changes.

**Comment by ErikSchierboom** [comment]
I'm also in favor of numerical ordering.

**Comment by Insti** [comment]
I'm fine with numerical ordering now that none of the cases are really exceptional.

**Comment by stkent** [comment]
@weibeld sounds like there's a consensus on one more ordering change (apologies!), and then this will be good to go :)

**Comment by weibeld** [comment]
Done :)

**Comment by stkent** [comment]
Thanks, @weibeld, nice work!

**Pull request merged**
