### PR TITLE
Moved track-level linting with configlet guidelines

### PR DESCRIPTION
**Pull request by aosdab**
Referencing issue [#27](https://github.com/exercism/docs/issues/27) in docs repo.

Hello. I deleted the track-level linting guidelines from CONTRIBUTING.md. However, this time, I did not remove the header and instead added a link to the [maintaining-a-track/](https://github.com/exercism/docs/tree/master/maintaining-a-track) directory in the docs repo as placeholder.

### CODE REVIEW

**Comment by kytrinyx** [comment]
@aosdab This should not include the commit that deletes the pull request guidelines. Are you comfortable with rebasing to remove the commit? (If not, there are probably people hanging out in the http://gitter.im/exercism/dev chat who could help out).

Since x-common does not rely on configlet, I think the heading/link about track level linting should be deleted entirely.

**Comment by aosdab** [comment]
Yeah, sorry about that. I will make the changes you recommended (deleting the heading), commit it, and rebase after -- removing the PR guidelines commit. Thanks for being patient with me

**Comment by Insti** [comment]
New location: https://github.com/exercism/docs/blob/master/maintaining-a-track/track-level-linting-with-configlet.md

**Comment by kytrinyx** [comment]
🎉 💛 ✨ 💛 🎉 Thank you @aosdab :-)

**Pull request merged**
