### PR TITLE
Removing unicode tests.

### PR DESCRIPTION
**Pull request by stevejb71**
Not all languages handle unicode well.

### CODE REVIEW

**Comment by petertseng** [comment]
https://github.com/exercism/x-common/pull/529#discussion_r98614292

**Comment by petertseng** [comment]
> Did you mean to remove a different test, or change the description?

I mean the commit message, sorry.

**Comment by petertseng** [comment]
> All of the characters in the test

1, null byte, 2, device control 3 (??? what is this???), 3, newline, 4, carriage return, 5, space, 6, tab, 7

**Comment by petertseng** [comment]
Why device control 3? That makes little sense. That does need to go away, regardless of what happens to the rest of the test case.

**Comment by petertseng** [comment]
Don't forget test version.

**Comment by stevejb71** [comment]
I'll take the \0003 out then.

**Comment by stevejb71** [comment]
OK, i'll remove the \u0013, and bump the version to 1.1.0.

**Comment by stevejb71** [comment]
For some reason though, I'm not keen on this test. I just felt it was a complication at the beginning, where I was keen to move on to the more interesting parts of the exercise. But I suppose others may feel differently.

**Comment by Insti** [comment]
👍 💯  On removing this test.

* It doesn't test anything relevant to the problem.
* the test name does not match the test contents.
* space is the only separators used in the test cases and we've already (implicitly) tested for that.

**Comment by stevejb71** [comment]
OK, I'm convinced... I'll change this to delete the test altogether.

**Comment by petertseng** [comment]
Nice!

**Pull request merged**
