### PR TITLE
Fix "Gigasecond: Schema Compliance"

### PR DESCRIPTION
**Pull request by kotp**
Reverts exercism/x-common#679

### CODE REVIEW

**Comment by kotp** [comment]
ref: #625

**Comment by tejasbubane** [comment]
I think we should do `Fix Compliance` instead of revert and then add new again.

**Comment by kotp** [comment]
Yeah, but I think we can work from this one.  This will mean less of a 'diff'.

**Comment by kotp** [comment]
Thanks @rbasso and @tejasbubane !

**Pull request merged**
