### PR TITLE
Clarify README for wordy

### PR DESCRIPTION
**Pull request by s2tephen**
Added explicit reference to order of operations to make instructions slightly clearer, see exercism/xjavascript#187

### CODE REVIEW

**Comment by kotp** [comment]
Don't you ignore the PEMDAS order of operations, but pay attention to the order of operations left to right, as you would speak and hear them, as clearly shown in the example?

Because your wording introduces "order of operations" it must be clear that you define that word in this context.  Prior to that, there should have been no miscommunication, only the error of reading into it more than what is there.

**Comment by kytrinyx** [comment]
I also find this confusing, but agree that if the original is also confusing, we need to fix it. Too jet lagged right now to constructively add to the conversation, I just wanted to add my support for the intent of the PR :)

**Comment by kotp** [comment]
I am for bringing this PR in... enough time has gone by for objections... and I think the change is appropriate.  Consider this a bump.

**Comment by IanWhitney** [comment]
Two 👍 were good enough for me to hit that merge button.

**Pull request merged**
